spring.application.name=ai-java-tutor

server.port=8080

spring.web.resources.add-mappings=false

logging.level.root=INFO
logging.level.com.example.aijavatutor=INFO

# ==========================================
# Judge0 configuration
# ==========================================

judge0.api-url=https://extra-ce.judge0.com
judge0.api-key=${JUDGE0_API_KEY:}
judge0.java-language-id=4

# ==========================================
# Gemini configuration
# ==========================================

gemini.api-key=${GEMINI_API_KEY:}
gemini.model=gemini-3.8-flash